const ACTIONS = {
    DOCLOGIN : 'DOCLOGIN',
    LOGIN: 'LOGIN',
    GET_DOCTOKEN: 'GET_DOCTOKEN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_DOCTOR: 'GET_DOCTOR',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_DOCTORS : 'GET_ALL_DOCTORS'
}

export default ACTIONS